KG-48 Game design without UI
tivelabs/memory-game pull request #1
Opened 2022-12-28 16:10 UTC by marcelotivelabs

memory-game code

2023-01-03 21:02 UTC, natalyTive approved these changes
I dont have more observations

2023-01-06 09:44 UTC, vbrianh requested changes

2023-01-06 09:44 UTC, vbrianh commented on __tests__/memoryGame.test.js
> +import MemoryGame from '../src/MemoryGame';
I have the next error:
![Screenshot 2023-01-06 at 05 38 44](https://user-images.githubusercontent.com/117357295/210974017-3bf60fbf-e50e-44c9-aef0-563403b59fb9.png)

2023-01-06 09:44 UTC, vbrianh commented on src/MemoryGame.js
> +  #verifyCardsSelected (x, y) {
remove unnecessary variable x, y and 0

2023-01-06 09:44 UTC, vbrianh commented on src/MemoryGame.js
> +};
remove unnecessary ;

2023-01-06 09:44 UTC, vbrianh commented on src/helpers/inputs.js
> +  return new Promise((resolve, reject) => {
remove unnecessary variable reject

2023-01-06 09:44 UTC, vbrianh commented on src/utils/validationUtils.js
> +import memoryConstants from '../constants/memory.js';
remove unnecessary variables

2023-01-06 19:33 UTC, marcelotivelabs commented on __tests__/memoryGame.test.js
> +import MemoryGame from '../src/MemoryGame';
It is fixed, please test again

2023-01-10 13:32 UTC, marcelotivelabs commented on src/MemoryGame.js
> +  #verifyCardsSelected (x, y) {
done

2023-01-10 13:33 UTC, marcelotivelabs commented on src/MemoryGame.js
> +};
done

2023-01-10 13:33 UTC, marcelotivelabs commented on src/helpers/inputs.js
> +  return new Promise((resolve, reject) => {
done

2023-01-10 13:33 UTC, marcelotivelabs commented on src/utils/validationUtils.js
> +import memoryConstants from '../constants/memory.js';
done

2023-01-10 20:50 UTC, vbrianh requested changes

2023-01-10 20:50 UTC, vbrianh commented on src/utils/validationUtils.js
> +const validCategory = (inputCategory) => {
remove unnecessary ; in line 8, 24, and 32

2023-01-10 20:50 UTC, vbrianh commented on src/MemoryGame.js
> +};
remove unnecessary ;

2023-01-10 20:50 UTC, vbrianh commented on src/MemoryGame.js
> +    let counter = null;
You can create this variable on the line 116

2023-01-11 15:32 UTC, vbrianh approved these changes
LGTM!

2024-06-28 09:28 UTC, merged